spring:
  datasource:
    url: jdbc:mysql://mysql:${SPRING_MYSQL_PORT}/fastats
    username: sixbackendcook
    password: ${SPRING_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10       # 최대 커넥션 수
      minimum-idle: 5             # 최소 유휴 커넥션 수
      idle-timeout: 600000        # 커넥션 최대 유휴 시간 (10분)
      max-lifetime: 1800000       # 커넥션 최대 수명 (30분)
      connection-timeout: 30000   # 커넥션 요청 최대 대기 시간 (30초)
      pool-name: HikariCP         # 풀 이름
  elasticsearch:
    # uris: http://elasticsearch-node1:${SPRING_ES_PORT_NODE1},http://elasticsearch-node2:${SPRING_ES_PORT_NODE2},http://elasticsearch-node3:${SPRING_ES_PORT_NODE3}
    uris: https://elasticsearch-node1:${SPRING_ES_PORT_NODE1}
    username: elastic
    password: ${SPRING_ELASTIC_PASSWORD}
    rest:
      ssl.enabled: true

  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}
      password: ${SPRING_REDIS_PASSWORD}
  ai:
    bedrock:
      llama:
        chat:
          model: ${OLLAMA_MODEL}
    ollama:
      chat:
        options:
          model: ${OLLAMA_MODEL}
      base-url: ${OLLAMA_BASE_URL}

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.web.client: INFO
    org.apache.http: WARN
    org.elasticsearch: WARN
    jdk.internal.httpclient: OFF  # HttpClient 로그 비활성화

server:
  port: ${SPRING_SERVER_PORT:8080}
  ssl:
    enabled: true
    key-store: file:/app/config/http.p12  # 인증서 경로 (src/main/resources 경로에 위치)
    key-store-password: *******  # 인증서 비밀번호
    key-store-type: PKCS12            # 인증서 타입 (JKS 또는 PKCS12)

OPENAPI:
  KEYS: ********************************
  URL: "https://kosis.kr/openapi/statisticsSearch.do?method=getList&format=json&apiKey={apiKey}&searchNm={tableId}"
